name: Robot Framework CEP Test

on:
  push:
    branches:
      - main
      - develop
  schedule:
    # Rodar a cada 10 minutos
    - cron: '*/10 * * * *'
  
  # Permite disparar manualmente
  workflow_dispatch:

jobs:
  test-opencep:
    runs-on: ubuntu-latest
    name: Teste OpenCEP

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-requests

      - name: Run OpenCEP tests
        run: |
          robot --outputdir results/opencep openCep.robot
        continue-on-error: true

      - name: Parse OpenCEP results
        id: opencep_result
        run: |
          if [ -f results/opencep/output.xml ]; then
            TOTAL=$(grep -o 'test count="[0-9]*"' results/opencep/output.xml | grep -o '[0-9]*' | head -1)
            PASSED=$(grep -o 'passed="[0-9]*"' results/opencep/output.xml | grep -o '[0-9]*' | head -1)
            FAILED=$(grep -o 'failed="[0-9]*"' results/opencep/output.xml | grep -o '[0-9]*' | head -1)
            
            echo "total=$TOTAL" >> $GITHUB_OUTPUT
            echo "passed=$PASSED" >> $GITHUB_OUTPUT
            echo "failed=$FAILED" >> $GITHUB_OUTPUT
          else
            echo "total=0" >> $GITHUB_OUTPUT
            echo "passed=0" >> $GITHUB_OUTPUT
            echo "failed=1" >> $GITHUB_OUTPUT
          fi

      - name: Upload OpenCEP results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: opencep-results
          path: |
            results/opencep/report.html
            results/opencep/log.html
            results/opencep/output.xml

  test-viacep:
    runs-on: ubuntu-latest
    name: Teste ViaCEP

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-requests

      - name: Run ViaCEP tests
        run: |
          robot --outputdir results/viacep viaCep.robot
        continue-on-error: true

      - name: Parse ViaCEP results
        id: viacep_result
        run: |
          if [ -f results/viacep/output.xml ]; then
            TOTAL=$(grep -o 'test count="[0-9]*"' results/viacep/output.xml | grep -o '[0-9]*' | head -1)
            PASSED=$(grep -o 'passed="[0-9]*"' results/viacep/output.xml | grep -o '[0-9]*' | head -1)
            FAILED=$(grep -o 'failed="[0-9]*"' results/viacep/output.xml | grep -o '[0-9]*' | head -1)
            
            echo "total=$TOTAL" >> $GITHUB_OUTPUT
            echo "passed=$PASSED" >> $GITHUB_OUTPUT
            echo "failed=$FAILED" >> $GITHUB_OUTPUT
          else
            echo "total=0" >> $GITHUB_OUTPUT
            echo "passed=0" >> $GITHUB_OUTPUT
            echo "failed=1" >> $GITHUB_OUTPUT
          fi

      - name: Upload ViaCEP results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: viacep-results
          path: |
            results/viacep/report.html
            results/viacep/log.html
            results/viacep/output.xml

  notify-teams:
    runs-on: ubuntu-latest
    name: Notificar Teams
    needs: [test-opencep, test-viacep]
    if: always()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download OpenCEP results
        uses: actions/download-artifact@v4
        with:
          name: opencep-results
          path: results/opencep
        continue-on-error: true

      - name: Download ViaCEP results
        uses: actions/download-artifact@v4
        with:
          name: viacep-results
          path: results/viacep
        continue-on-error: true

      - name: Parse results
        id: parse
        run: |
          # OpenCEP
          if [ -f results/opencep/output.xml ]; then
            OPENCEP_TOTAL=$(grep -o 'test count="[0-9]*"' results/opencep/output.xml | grep -o '[0-9]*' | head -1)
            OPENCEP_PASSED=$(grep -o 'passed="[0-9]*"' results/opencep/output.xml | grep -o '[0-9]*' | head -1)
            OPENCEP_FAILED=$(grep -o 'failed="[0-9]*"' results/opencep/output.xml | grep -o '[0-9]*' | head -1)
            OPENCEP_STATUS="✅ FUNCIONANDO"
          else
            OPENCEP_TOTAL=0
            OPENCEP_PASSED=0
            OPENCEP_FAILED=0
            OPENCEP_STATUS="❌ FALHA"
          fi

          # ViaCEP
          if [ -f results/viacep/output.xml ]; then
            VIACEP_TOTAL=$(grep -o 'test count="[0-9]*"' results/viacep/output.xml | grep -o '[0-9]*' | head -1)
            VIACEP_PASSED=$(grep -o 'passed="[0-9]*"' results/viacep/output.xml | grep -o '[0-9]*' | head -1)
            VIACEP_FAILED=$(grep -o 'failed="[0-9]*"' results/viacep/output.xml | grep -o '[0-9]*' | head -1)
            VIACEP_STATUS="✅ FUNCIONANDO"
          else
            VIACEP_TOTAL=0
            VIACEP_PASSED=0
            VIACEP_FAILED=0
            VIACEP_STATUS="❌ FALHA"
          fi

          echo "opencep_total=$OPENCEP_TOTAL" >> $GITHUB_OUTPUT
          echo "opencep_passed=$OPENCEP_PASSED" >> $GITHUB_OUTPUT
          echo "opencep_failed=$OPENCEP_FAILED" >> $GITHUB_OUTPUT
          echo "opencep_status=$OPENCEP_STATUS" >> $GITHUB_OUTPUT

          echo "viacep_total=$VIACEP_TOTAL" >> $GITHUB_OUTPUT
          echo "viacep_passed=$VIACEP_PASSED" >> $GITHUB_OUTPUT
          echo "viacep_failed=$VIACEP_FAILED" >> $GITHUB_OUTPUT
          echo "viacep_status=$VIACEP_STATUS" >> $GITHUB_OUTPUT

      - name: Send Teams notification
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URI }}
          notification-color: 3088aa
          title: "🔍 Teste de API CEP"
          description: |
            **OpenCEP** ${{ steps.parse.outputs.opencep_status }}
            • Total de CEPs testados: ${{ steps.parse.outputs.opencep_total }}
            • CEPs com sucesso: ${{ steps.parse.outputs.opencep_passed }}
            • CEPs com falha: ${{ steps.parse.outputs.opencep_failed }}

            **ViaCEP** ${{ steps.parse.outputs.viacep_status }}
            • Total de CEPs testados: ${{ steps.parse.outputs.viacep_total }}
            • CEPs com sucesso: ${{ steps.parse.outputs.viacep_passed }}
            • CEPs com falha: ${{ steps.parse.outputs.viacep_failed }}